name: C/C++ CI

on:
  push:
    branches: [ "main", "development", "experimental", "test*", "feat*", "bug*" ]
  pull_request:
    branches: [ "main", "development", "experimental", "test*", "feat*", "bug*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-22.04, ubuntu-latest, macos-latest, macos-14 ]
        python-version: [ "3.10", "3.12" ] # Note: 3.14 causes issues with Neuron 8.2.7

    steps:
    - uses: actions/checkout@v6
    
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version:  ${{ matrix.python-version }}

    - name: C++ info
      run: g++ -v

    - name: Install graphviz
      uses: ts-graphviz/setup-graphviz@v2
      with:
        # Skip to run brew update command on macOS.
        macos-skip-brew-update: 'true' # default false

    - name: Install dependencies (Ubuntu)
      run: sudo apt-get install -y nlohmann-json3-dev tree graphviz openjdk-11-jdk
      if: ${{ contains(matrix.runs-on, 'ubuntu') }}

    - name: Install dependencies (macOS)
      run: brew install nlohmann-json tree
      if: ${{ contains(matrix.runs-on, 'macos') }}

    
    - name: Run C++ tests 
      run: |
          make tests
          ./tests

    - name: Test makefile
      run: make

    - name: Install Python requirements
      run: |
        pip install setuptools==80 # needed for Neuron on py >=3.12
        pip install NEURON==8.2.7
        pip install OSBModelValidation pyNeuroML
        pip install numpy matplotlib scipy modelspec
        pip install ipywidgets
        pip install ruff
        
        pip list

        which nrnivmodl
        nrnivmodl 
        
    - name: Test C++/Python interactions
      run: |
        cd test_files
        ./test.sh 
        cd modelspec_api
        ./test.sh
        
    - name: Test directly running main program
      run: |
        ./main -p 6  # Note: small population of 6 for quick runtime
        ls -alth

    - name: Test Python command line script
      run: |
        python run_main.py -R 1233 -p 6 --doEvol --outputFolderName exampleRun2  # Note: small population of 6 for quick runtime

    - name: Test using test_all.sh
      run: |
        which nrniv
        export NEURON_HOME=$pythonLocation
        env
        
        ./test_all.sh # also generated neuroml

        git diff exampleRun/phenotype.dat 

      
    - name: list generated files
      run: |
          ls -alth
          tree
          pip list
